const constants = {
  DATA_SOURCE: 'DATA_SOURCE',
  APPLICATION_REPOSITORY: 'APPLICATION_REPOSITORY',
  ADDRESS_REPOSITORY: 'ADDRESS_REPOSITORY',
  VEHICLE_REPOSITORY: 'VEHICLE_REPOSITORY'
}

export default constants